apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-deploy
  labels:
    app: reverse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reverse
  template:
    metadata:
      labels:
        app: reverse
    spec:
      containers:
      - name: reverse
        image: reverse-string
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-service
spec:
  type: LoadBalancer
  selector:
    app: reverse
  ports:
    - name: http
      protocol: TCP
      port: 52396        # external service port (what host will hit)
      targetPort: 5000  # container port in pods
